# Generated by Django 3.2.3 on 2021-06-03 15:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('budgeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saving',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 6, 3, 15, 17, 22, 39800)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='saving',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
            preserve_default=False,
        ),
    ]
