# Generated by Django 3.2.3 on 2023-04-16 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_project_is_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='is_clone',
            field=models.BooleanField(default=False),
        ),
    ]
